### ISSUE TITLE
'Failed to load accounts.txt'

### ISSUE THREAD

**Issue by matthew-lowe** [MCGoSnipe/MCGoSnipe#3]
Since 'accounts.txt' is in the .gitignore, I'm assuming it contains the account to snipe the name with, but there's nothing in the documentation about how it should be formatted or that it should be created in the first place.

**Comment by overestimate** [comment]
Duplicate of #2.

**Comment by overestimate** [comment]
For reference, accounts should be loaded with the example shown in `accounts.txt.example`.
